### ISSUE TITLE
Wondering if title should be removed from widgets

### ISSUE THREAD

**Issue by camilodelvasto** [moxie-leean/wp-widgets#21]
The widget title is a standard WP thing, but can get on the way of the developer and WP admin (especially for pretty customized widgets having many fields) when creating new widgets using ACF.

My proposal is to remove the 'title' field altogether and allow ACF to control all the fields in the widget - this way all the field description, placeholder, etc. goes to just one place, the ACF group defining the fields.

**Comment by mitogh** [comment]
I agree with some of this @camilodelvasto 

I think if we already have a default field for title same as pages / posts we should use that unless is not required we should get ride of the title on scenarios where is not used but I think the title it allow to identify the widget but can be used as a data field as well.

**Comment by camilodelvasto** [comment]
The main benefit I see is the following: we are already loading the fields from another file, the ACF group, and we are rendering the template using a partial - that means we could almost leave that widget file untouched and would have a central location for all field things related - much leaner imo

**Comment by mitogh** [comment]
The thing is all WP Widgets should have a field in order to present the save button. What we can do in order to improve the speed of the creation of a new widget is: 

Define a class that already implements the title and other repetitive things on all widgets, like registration.

And just having one method that needs to be implemented for example: 

``` php
class MyWidget extends \LeanWidget {
    public function UI( $instance ) {
       the_field( 'Field 1', $this->widget_id );
       the_field( 'Field 2', $this->widget_id );
    }
}
```

**Comment by adamf321** [comment]
We already have that @mitogh :-)  It's the AbstractWidget in wp-wdigets.

**Comment by mitogh** [comment]
Closing this one then.

We need to update the docs and some code in order to make it more easier to use.
